### ISSUE TITLE
Chef::Source::<klass> specs to be orthogonal

### ISSUE THREAD

**Issue by taqtiqa-mark** [applicationsonline/librarian#109]
The spec suite of a `Chef::Source::<klassA>` should not fail if some other `Chef::Source::<klassB>` is broken.  Example issue #23

One fragile point is in [here](https://github.com/applicationsonline/librarian/blob/master/lib/librarian/lockfile/parser.rb#L25)

**Comment by yfeldblum** [comment]
I agree. They should be orthogonal to each other.

The source specs are currently marked as functional tests, but the way they are implemented is as integration tests because they are tested indirectly via a full top-to-bottom simulation. That's why in practice these tests may not be orthogonal.

One of the things I'd like to do is to convert those to specs that only exercise code from the sources and from their dependencies, but does not exercise code that depends on the sources, such as the DSL, the top-level actions, or the CLI.

**Comment by taqtiqa-mark** [comment]
Agreed, right now this is starting to look like Bundler's spec suite, which is nigh impossible for outside contributors to work with - too much implicit behavior that is revealed only when you add/extend features.

As I work on issue #40 I'm going to push changes related to #109 in to the branch `feature/issue_109`  I think when issue #40 is closed it will be a reasonable time to merge the `feature/issue_109` branch.  I aim to track `feature/issue_109` as I work on issue #40, so everything should merge cleanly.

Once done I think we can then look at re-factoring into unit specs as you suggest.

**Comment by yfeldblum** [comment]
After splitting librarian-chef out, I don't think this is an issue anymore. Everything except the git-source functional specs relies (or should rely) on the mock source, which is just not allowed to be broken. And the git-source functional spec does not use the dsl or lockfile.
