### ISSUE TITLE
Local modifications in cookbooks don't get pulled when cooking with knife solo

### ISSUE THREAD

**Issue by mostr** [applicationsonline/librarian#132]
I have a community cookbook downloaded via Librarian and I made a modification in this cookbook. When using `knife solo cook` those local modifications are not pulled up, instead original version donwloaded by librarian (from `tmp/librarian/cache` is transferred to server and run. 

Is there any way to apply local modifications without creating own official cookbook and without clearing cache before every cooking?

**Comment by yfeldblum** [comment]
There are various options.
- Use your own fork of the upstream cookbook and reference it with the `:git` source in your `Cheffile`.
- Use multiple cookbook paths and rely on cookbook file-level shadowing.
- Use a "supervisor" recipe of your own which sets up attributes, includes the target recipe, and then rewrites existing resources declared in the target recipe.

**Comment by mostr** [comment]
So what is the reason Librarian puts cookbooks in two places: `cookbooks` dir and in `tmp/librarian/cache`? What is the `cookbooks` version used for then if `cache` version gets applied when cooking? 
Regarding file-level shadowing, even if I modify `solo.rb` by adding one more path to `cokbook_path` it doesn't get picked up. Tried with different paths' order.

The only way I managed to apply my local modification was to temporarily rename `Cheffile` so that it doesn't discover Librarian is in use.

It'd be great to allow local modifications to be applied without need for separate git repo, etc. I'm just playing around with chef and don't want to fork every cookbook I try. But I don't know yet if this is something to be done by librarian or by knife itself.

**Comment by yfeldblum** [comment]
Librarian-Chef expects that you will use `librarian-chef install` to fetch the cookbooks listed in `Cheffile.lock` and place them into `./cookbooks` (or another directory of your choosing - it's configurable). Then `chef-solo` and `knife` can both be configured to pick up the cookbooks from `./cookbooks` as well as from another directory too.

You can use a separate `site-cookbooks` directory for your own cookbook shadow files, which are files that replace corresponding files found in `cookbooks` when you `knife cookbook upload` etc. You don't need to tell Librarian-Chef about this `site-cookbooks` directory. You just add it to your `.chef/solo.rb` or `.chef/knife.rb`.

The way Librarian-Chef works, it caches plenty of stuff in `tmp/librarian/cache`, including JSON responses from the Community Site as well as targz'd and extracted cookbooks. It caches these items whenever they get fetched from remote sources, so that the next time around, those items that would otherwise have been fetched remotely can be read from disk much more quickly. For example, these caches are used to speed up `librarian-chef install`, as well as other commands. However, that's all internal details.

There's also an integration where Librarian-Chef will, on every `chef-solo` or `knife` command, install the cookbooks into a temp directory, and where you add that temp directory to your `.chef/solo.rb` or `.chef/knife.rb`.

Unfortunately, I'm not sure how `knife-solo` works, which is what I assume you're using, and how `knife-solo` interacts with these features.

**Comment by mostr** [comment]
Many thanks for quick and detailed response.

It turns out that `knife-solo` has `--no-librarian` option which grabs cookbooks from regular paths bypassing Librarian. It seems to be partial solution to my problem, but need to keep in mind that every `knife-solo` run without `--no-librarian` option will overwrite all local changes in `cookbooks` dir with those from `tmp/cache`.
