### ISSUE TITLE
error in Cheffile github url wipes local mods and leaves user in anon branch

### ISSUE THREAD

**Issue by bluekelp** [applicationsonline/librarian#140]
_(verified this is present in latest librarian-chef gem available via "gem install librarian-chef --pre" also)_

if user enters a :github => URL for a repo as **https://github.com/owner/repo** instead of **owner/repo** and runs _librarian-chef update_ the tool fails with this message:

> No metadata file found for aws from https://github.com/http://github.com/owner/repo#master! If this should be a cookbook, you might consider contributing a metadata file upstream or forking the cookbook to add your own metadata file.

the local index has been reset, local mods lost (even those staged via add), and the owning project's branch switched to an anonymous/headless branch (e.g., from master). i was unable to figure out how to recover my lost changes.

e.g., my project, foo, is in git and contains a chef/ dir which contains the Cheffile and its managed cookbooks/ dir.  the **foo** repo is the one being messed up by the typo in the Cheffile.

**Comment by cmur2** [comment]
I stumbled into this too because of a silly typo in my Cheffile.

The behavior of librarian-chef (local index reset, local changes lost, branched switched into nirwhana) is **NOT**  acceptable! A nice error message explaining what gone wrong where would be helpful but no destructive operation in the parent repository librarian-chef has nothing to do with!

I'm using librarian (0.0.26).

**Comment by yfeldblum** [comment]
Should be fixed in https://github.com/applicationsonline/librarian/commit/dfc57c20e3a782365a458bff563c1ced85eeaa8e.
