### ISSUE TITLE
Feature: Submit patch via upstream issue (Github specific)

### ISSUE THREAD

**Issue by hedgehog** [applicationsonline/librarian#31]
I like that Librarian just grabs the cookbooks, I have tried submodules and they don't work in this situation - far to much fiddling and untangling the inevitable mess is a real pita.

Nonetheless, it would be nice to allow people to easily contibute changes back to the upstream cookbook.  In github this is possible, via the issues API.  Essentially Librarian would (non-trivial):
- Build a diff of the current local cookbook from what is pointed to in the `Cheffile`
- Open an issue and place the diff in the issue.  Not ideal I know but at least allows people to get their contributions back in one painless step, i.e. they don't have to have a fork.  But they do have to have a Github account.

The command might look like

```
librarian-chef issue <cookbook-name>
```

In order to open an issue librarian would need to have access the users Github OAuth2 token, say through `ENV['GITHUB_TOKEN']`.  No token no push of the patch.
Of course this is very Github specific, but other avenues might open later, e.g email the patch.

The idea is to make it dead easy for people to push back what changes they have made that work for them.  Cookbook maintaners/authors could pick and chose as they wish.

Thoughts

**Comment by yfeldblum** [comment]
I certainly want to help make things dead easy. Thanks for the suggestion! However, this is beyond the scope of Librarian.

The explicit intention of Librarian is that it should ignore whatever changes you might make to a Librarian-managed install path and/or overwrite your changes with the canonical version of the dependency as retrieved from the specified source.

There isn't an easy way to integrate Librarian resolving, fetching, and managing all the third-party dependencies you use with you modifying those dependencies. They are opposite workflows. Librarian expects that every change to a dependency comes from upstream.

If you're forking and modifying a third-party cookbook dependency, one option is to vendor it into your chef-repo in the style of `knife cookbook site install` and switch to the `:path =>` source (instead of the `:site =>` or default source) for that cookbook. Then you can make changes to that cookbook, track them in git, maintain a history of commits, and push those commits upstream. You would use the standard tools for this, such as `git format-patch` or GitHub pull requests.

This works because, to the `:path =>` source, the path where you vendor a cookbook is the upstream. Note, however, that every time you make a change to a vendored cookbook where you use the `:path =>` source, you will have to re-run `librarian-chef update NAME` to get that updated cookbook into the Librarian-managed cookbooks directory.

**Comment by hedgehog** [comment]
OK I see your point.  I suppose the ideal would be to be able to work on cookbooks with just one tool.  For the reasons you state that is `git` at the moment.  But the `:path =>` option looks enticing :)
