### ISSUE TITLE
disentangle source-control from packaging

### ISSUE THREAD

**Issue by hedgehog** [applicationsonline/librarian#41]
Remove `git ls-files` from the gemspec.

I think this is one of those religious issues....

I get the value added of 'only release commited files'. But to me having git commands in your gemspec is a "code-smell" (these kids come up with crazy phrases). Essentially I'd argue you should be releasing a pure master or release branch, and that branch should have what is released, no-more-no-less. If you have files, etc that shouldn't be released these should be in the excludefiles for the development branch. Git's branching, squash commits, rebase etc means you can keep release/master neat while all the stuff that shouldn't be released is in the development branch.

See here for some details (no doubt google will throw up more): 
http://cogniton-mind.tumblr.com/post/1423976659/howto-gitignore-for-different-branches

**Comment by yfeldblum** [comment]
It is one of those religious issues.

I would say that I am not a fan of having an enforced pure release branch (while it is often convenient to refactor things or develop new features in branches, that is usually an ad-hoc or case-by-case decision for me). Moreover, given the current size, scope, and contributors to librarian, it would be more ceremony than seems to me to be warranted right now.

I do think it is important to enforce that no file is included unintentionally in a release that should have been ignored. The canonical list of which files are part of the project is, at the moment, git, and so no file should make it into a release that I have not explicitly added to git. (I don't do `git add .`, without at least first verifying via `git status` that that would only add files I want.) It is a safeguard against doing stupid things that would otherwise be easy to do by mistake, and hard to guard against. It is a safeguard against, e.g., accidentally having editor swap files or rubinius compiled files being gitignored but accidentally included in a release. I do understand that I could set up per-branch excludesfiles and not set them up in master, which would help, but it doesn't help against global gitignore files and, for me, it would be too much ceremony.

I recognize that there are a number of problems with shelling out to git from the gemspec. But this is tradeoff. What would the benefits be of moving away from that, and how would one compensate for the benefits lost by moving away from that, without introducing more ceremony than is warranted?

**Comment by hedgehog** [comment]
It was quite difficult to disentangle some of the assumptions and logic in a brief response, and after drafting a long response, I think it is better suited to a blog post on this topic.
This is not the first time I've raised this objection, and you are not alone in rejecting it :)

Feel free to close the issue if your mind is made up.

**Comment by yfeldblum** [comment]
My mind is not made up. But the needs are made up.
- Canonical whitelist of files. No blacklist.
- Simple process for simple projects. Or no process.

**Comment by yfeldblum** [comment]
Possibilities abound.

**Comment by yfeldblum** [comment]
I pushed 2e7b228100ccc7b3a22a8c9973d78b72cefec9af.

Does this get any closer to what you were thinking?

**Comment by hedgehog** [comment]
Sorry for the delay, this slipped.  I knew it wasn't the `git` command currently in the `.gemsepc`, I was a little surprised how tricky it was to actually do what people want in their `.gemspec`.... so what you are trying to do with git in the `.gemspec` is not trivial.  
To be sure you have the effect you desire, you'd need to do something like this:

http://stackoverflow.com/a/9370094/152860

I'd need to spend more time looking at  #2e7b228 to see if it handles that.

**Comment by yfeldblum** [comment]
What #2e7b228 does is it patches Bundler's gem-building task to:
- Build a compiled gemspec first. The compiled gemspec does not shell out to git. Instead, the shelling-out to git is done in the process of compiling the compiled gemspec.
- Use the compiled gemspec when creating a packaged gem file.

This works with `rake build`, which is the expected way to build this particular repository into a gem, and `rake install` and `rake release`.

**Comment by hedgehog** [comment]
Okay, so the `git` issues remain.  I'd like to write up the gotchas as a blog post but time is prooving tight.  The SE link above has a workaround that is robust, but ugly.  Hence the preference for using a dev branch and building off a clean master.
