### ISSUE TITLE
Feature: git://... support

### ISSUE THREAD

**Issue by hedgehog** [applicationsonline/librarian#43]
This might be worth adding since people instinctively seem to think the git protocol is supported:

https://github.com/hedgehog/chef-rbenv/commit/2cdbf04791189a7cb8871ce29c625d8590c3c238

**Comment by yfeldblum** [comment]
Any thoughts on what is currently deficient and what this support would take?

**Comment by everm1nd** [comment]
https:// protocol requires additional authorization. If I change some cookbook and make commit right from cookbooks folder, then github asks my login/password. It's very annoying. Please, fix it.

**Comment by yfeldblum** [comment]
@everm1nd It sounds like you're using librarian-chef in a way that is not intended, is not supported, and will be removed. There is an issue out there to strip out the .git directory from installed cookbooks (cookbooks copied to the `cookbooks/` directory).

Librarian-chef is really for fetching third-party cookbooks. If you're often working on cookbooks right from your cookbooks folder, you should actually not be using librarian-chef with those cookbooks. You should probably have those cookbooks in a separate directory like `site-cookbooks/` that librarian-chef doesn't know about, perhaps even using git submodules.

I would like to support the use of [deploy keys](#2), so that you can use a private key copied into the Cheffile (or, next to the Cheffile) to fetch a cookbook from a private repository. (A [deploy key](http://help.github.com/deploy-keys/) is a private key to which are attached read permissions on a single repository. Every repository must have a different deploy key, and pushing is not allowed with a deploy key. Users must only use their own keys, never deploy keys. Obviously librarian-chef can't really enforce any of this.)

I may also like to support fetching cookbooks using whatever is in `~/.ssh`, but I think that's not generally a good practice.

**Comment by yfeldblum** [comment]
@hedgehog I cannot replicate on librarian master. It should support `git://` syntax just fine.

**Comment by hedgehog** [comment]
OK. I am flat chat elsewhere right now so am closing this.  Will reopen if I get to replicate what happened.
