### ISSUE TITLE
Cloning from private repo

### ISSUE THREAD

**Issue by smdern** [applicationsonline/librarian#48]
I'm trying to use cookbooks stored in a private repo. Git isn't using my ssh key. Any suggestions for getting around this?

**Comment by yfeldblum** [comment]
Tricky.
1. Vendor the private repo/cookbook, perhaps manually or perhaps using `git submodule`, and, in your `Cheffile`, use either the `:git =>` source or the `:path =>` source pointing to a local relative path.
2. Help with #2. I'm not sure how to write automated tests for this, because I'm not sure how to set up a git-ssh server locally without requiring root access.

**Comment by smdern** [comment]
I actually just used the git url instead of https and it worked. :)
