### ISSUE TITLE
Feature: `librarian-chef init-run-list` build Cheffile from run-list

### ISSUE THREAD

**Issue by christianchristensen** [applicationsonline/librarian#5]
It would be cool given chef roles if the run-lists could be detected and then used to build the initial cookbook inclusions that are in the Cheffile.
## Notes:
-  https://github.com/opscode/chef/blob/master/chef/lib/chef/run_list.rb#L136-140
-  https://github.com/opscode/chef/blob/master/chef/lib/chef/run_list/run_list_expansion.rb#L150-158

**Comment by christianchristensen** [comment]
Bonus points for run-list detection from a Vagrantfile (this should probably be a plugin not something built in).

**Comment by yfeldblum** [comment]
Thanks for the suggestion.

Some questions arise:
- How would librarian-chef know what your chef-server is?
- How would librarian-chef get credentials for your chef-server?
- How would librarian-chef determine which node's run-list you want?
- How would librarian-chef handle multiple nodes with conflicting run-lists? (That is, multiple nodes with run-lists containing the same cookbook name but different versions?)
- How would librarian-chef know which sources to pull the cookbooks from?
- How would librarian-chef know whether or not the cookbooks are from an external source or are your custom cookbooks or your customizations on cookbooks from external sources?
- How would librarian-chef know what your version constraints are?
- How would librarian-chef know which cookbooks it should include in the Cheffile, and which should be resolved and locked into the Cheffile.lock?

It seems to me that this suggestion brings up all these questions because it inverts librarian-chef's intended "flow" of cookbooks. Librarian-chef currently has no knowledge of a chef-server. Librarian-chef is built around you telling it what cookbooks you need so that you can get them into the chef-server using knife, rather than you telling it what chef-server you have so that it can tell you what cookbooks you have.

If you're simply looking for a way to get the expanded list of recipes from your chef-server, you can do that with knife:

```
$ knife node show #{node_name} -a recipes
```

You can easily copy the cookbook names (leaving out the recipe names) into a new `Cheffile` created with `librarian-chef init`. So long as all of the cookbooks in question are uncustomized and come from the Opscode Community Site, and so long as they all correctly declare their dependencies in their `metadata.rb` files, and so long as you are OK with the latest versions, you can run `librarian-chef install` to create your `Cheffile.lock` and copy the cookbooks to your `./cookbooks` directory, and `knife cookbook delete --all && knife coobook upload --all` to get your cookbooks into the chef-server. You can also edit the `Cheffile` to include your own version constraints and sources for particular cookbooks, in case you have version constraints or in case some of your cookbooks need to come from a different place, before running `librarian-chef install`.

**Comment by christianchristensen** [comment]
Thank you for the detailed reply!

You are absolutely correct "because it inverts librarian-chef's intended "flow"" and I agree; maybe this behavior belongs in a rake task or some helper script outside of librarian. Given your example use case of using knife to get the recipes from the node that would be simple enough (I am just trying to automate that step - which may be out of the scope of this project).

The use case I had intended: (I frequently use Vagrant for quick setup): take a setup like [rails-quick-start](https://github.com/opscode/rails-quick-start/tree/master/roles) where there are roles predefined - given they have the cookbooks in the runlist that I would likely just be copying over - I was thinking the init task (since it is just a template copy) could init with the runlist items from there.

All-in-all thanks for humoring me... I know its a pretty petty use case - thanks!

**Comment by yfeldblum** [comment]
I am marking this issue as outside the scope and closing it. But thank you for the suggestion!

Librarian-chef generally assumes that you will be writing a Cheffile and keeping it in source control just as much as you will be writing a role and keeping it in source control. You can certainly copy-and-paste a little bit in both cases. Overall, I think it would be outside the scope of this project to try to automate a Cheffile based on outside data sources and some computer intuition.

The intention really is to replace the `knife cookbook site install` workflow (by letting you declare a dependency on a cookbook rather than vendoring the cookbook) and the workflow using a forked and patched bundler and the `cc.gemspec`s (by authoring a tool designed to cover this case rather than patching an existing tool to cover it).

As always, if you have any more suggestions or catch any bugs, please post a new issue!
