### ISSUE TITLE
Assume yes on librarian-chef install

### ISSUE THREAD

**Issue by smdern** [applicationsonline/librarian#52]
Is there any way to force yes for librarian-chef installs? For example RSA key fingerprint.

**Comment by yfeldblum** [comment]
In this case, git and ssh are protecting you against a man-in-the-middle attack. While such attacks are pretty rare; but they'd be devastating if one really got to you. Best to collect the server keys by hand ahead of time. Otherwise, someone can publish a truly evil recipe and perform a man-in-the-middle attack, which will compromise people's machines.
