### ISSUE TITLE
Removes ./cookbooks/.gitkeep

### ISSUE THREAD

**Issue by leehambley** [applicationsonline/librarian#72]
I don't know if it's particularly important, but I prefer to add `tmp` and `cookbooks` as empty repositories to my project, and check into these directories a `.gitkeep` file, so that Git will retain the empty directory.

When using `librarian-chef install` (note without `--clean`) the .gitkeep file is removed.

I'd be happy to accept "that's just the way this library works" - but it's a valid point, I feel, fine if your tool really wants to manage that whole directory, but I think a `.gitkeep` file is a widely enough enjoyed paradigm to warrant opening an issue to start the conversation.

Please consider this a feature/discussion request, and in no way a critical issue.

**Comment by yfeldblum** [comment]
Is there a specific need for a `.gitkeep` directory? For example, is there other stuff out there that's breaking because the one file is missing? There's no specific reason for Librarian-Chef effectively to `rm -rf cookbooks/` rather than effectively to `rm -rf cookbooks/*`. It just happened to be easier to do it the first way at the time.

TS;DR

Some people start off thinking of Librarian-Chef as a tool that can help you manage your `cookbooks/` directory. There are various tools that _help_ you manage it, but that's not how Librarian-Chef is designed.

If you use Librarian-Chef, you are agreeing to Librarian-Chef taking over complete ownership of your `cookbooks/` directory. You are also agreeing to run `librarian-chef install` before using your `cookbooks/` directory, so that Librarian-Chef can prepare it for you. Given that you have ceded to Librarian-Chef the control over your `cookbooks/` directory, and that you have run `librarian-chef install` and now have a prepared `cookbooks/` directory for any subsequent activity, what do you need a `cookbooks/.gitkeep` for?

If you use Librarian-Chef, your `cookbooks/` directory is no longer part of your source control. It is a built artifact that comes from a build step. Feel free to vendor its contents into git if you like - no harm in doing that. It's kind of like vendoring gems when you use Bundler, or vendoring built jars or fetched jars into git. There are certainly cases where vendoring the built artifacts is the best approach.

**Comment by leehambley** [comment]
@yfeldblum That's exactly the kind of clarification I was looking for, thank you for that.

Like I said, I prefer normally to keep such directories (which are supposed to be empty, and managed) managed in source control, with a `.gitkeep` so that my team recognize that there's an empty directory, and they probably need to do something, but I absolutely accept your answer, and have dropped the `.gitkeep` file.

Thanks again.

**Comment by yfeldblum** [comment]
Thanks for using Librarian-Chef and for opening the issue! If I can clarify anything else for you, or if you run into any other issues or have any other feature suggestions, please let me know.
